### ISSUE TITLE
Dialog component overlay on grid component is not modal. 

### ISSUE THREAD

**Issue by jlu344** [telerik/kendo-angular2#168]
Some rows and header still display active

![image](https://cloud.githubusercontent.com/assets/20970105/21770857/23bbfd16-d653-11e6-9533-18265c16e36d.jpg)

**Comment by lucifercha** [comment]
i have the same question

**Comment by gyoshev** [comment]
The problem is caused by a missing `z-index` in the component styles. This has been fixed in the latest theme. Please note that the theme package has been renamed to `@progress/kendo-theme-default` -- see the updated instructions in the [Getting Started help topic](www.telerik.com/kendo-angular-ui/getting-started/) to install the latest version of the theme.

**Comment by jlu344** [comment]
I updated with the latest theme package and its still an issue..

![image](https://cloud.githubusercontent.com/assets/20970105/21873826/2e3c27aa-d83f-11e6-88bd-2c2b18be4065.png)

![image](https://cloud.githubusercontent.com/assets/20970105/21873837/45856444-d83f-11e6-8eff-64252aedfdf1.png)

![image](https://cloud.githubusercontent.com/assets/20970105/21873874/8236d634-d83f-11e6-9895-612932c12c2c.png)

**Comment by gyoshev** [comment]
It appears that the project is using the correct theme.

I tried reproducing the problem in [this plunkr](http://plnkr.co/edit/D02ECXOUxr9Hsff6x6Qd?p=preview), but it didn't show. Can you please adjust it so that it shows the problem?

**Comment by jlu344** [comment]
I believe I found the issue..  I created a angular component that has a kendo dialog component.  When I nest this component in a Kendo Grid Toolbar and try to display, the dialog the issue occurs.  When I remove it from the Toolbar, my dialog displays correctly.

I also have the Kendo Grid nested with in a Kendo Tab Strip.  Not sure if this causes an issue also, but I can do a work around for now..

Thanks..  

      <kendo-tabstrip>
                <kendo-tabstrip-tab [title]="'Blood'" [selected]="selectedTab">
                    <template kendoTabContent>                     
                           <p *ngIf="!samples"><em>Loading...</em></p>
                            <kendo-grid [data]="gridView"
                                        [height]="400"
                                        [selectable]="false"
                                        [scrollable]="true"
                                        [sortable]="{ mode: 'multiple' }"
                                        [sort]="sort"
                                        [pageSize]="pageSize"
                                        [skip]="skip"
                                        [pageable]="true"
                                        (sortChange)="sortChange($event)"
                                        (selectionChange)="onGridChange($event)"
                                        (pageChange)="pageChange($event)">
                                <kendo-grid-toolbar>
                                        <div class='col-sm-2' style="text-align:right">
                                            <excel-download></excel-download>                                         
                                        </div>

**Comment by gyoshev** [comment]
@jlu344 I tried reproducing the said issue in [this plunkr snippet](http://plnkr.co/edit/OwsskSKRB28R5EWwI8Tn?p=preview), with both a TabStrip and placing the dialog in the grid toolbar. Can you modify the sample so that it shows the problem, so that we can devise a fix?

**Comment by gyoshev** [comment]
I am closing this until we get a runnable sample that allows us to reproduce the issue. Feel free to provide one so that this can be resolved.

**Comment by ananyakumar-0247** [comment]
I also have the Kendo Grid nested with in a Kendo Tab Strip. Not sure if this causes an issue also, but I can do a work around for now.. , i am facing this issue as well
